apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: modelserver2-dec19-1 
  janus-idp.io/tekton: modelserver2-dec19-1
  backstage.io/kubernetes-id: modelserver2-dec19-1
  backstage.io/kubernetes-namespace: modelserver2-dec19-1 
  app.kubernetes.io/part-of: modelserver2-dec19-1
resources: 
- application-dev.yaml